from __future__ import annotations
from pathlib import Path
from datetime import datetime
import time
import sys

PROMPT_DIR = Path(".")
OUTPUT_FILE = PROMPT_DIR / "FULL_PROMPT.txt"

# ✅ Explicit order = deterministic build
ORDER = [
    "0_systemrules.txt",
    "0B_entitydefinitionrules.txt",
    "1_notetypestructure.txt",
    "2B_wholesourcecoverageaudit.txt",
    "2C_coresummaryrule.txt",
    "3_cardtypesrules.txt",
    "imagerules.txt",
    "4_Unknown.txt",
    "5_differentialdrillsrules.txt",
    "6_mechanism.txt",
    "7_boardstrap.txt",
    "8_highyield.txt",
    "9_radiopediadrill.txt",
    "outputrule.txt",
]

LABELS = {
    "0_systemrules.txt": "SYSTEM RULES",
    "0B_entitydefinitionrules.txt": "ENTITY DEFINITION RULES",
    "1_notetypestructure.txt": "NOTE TYPE STRUCTURE",
    "2_corevalidationgate.txt": "CORE VALIDATION GATE",
    "2B_wholesourcecoverageaudit.txt": "WHOLE SOURCE COVERAGE AUDIT",
    "2C_coresummaryrule.txt": "CORE SUMMARY RULE",
    "3_cardtypesrules.txt": "CARD TYPES + TRIGGERS",
    "imagerules.txt": "IMAGE RULES",
    "4_Unknown.txt": "UNKNOWN CARD RULES",
    "5_differentialdrillsrules.txt": "DIFFERENTIAL DRILL RULES",
    "6_mechanism.txt": "MECHANISM CARD RULES",
    "7_boardstrap.txt": "BOARDS TRAP RULES",
    "8_highyield.txt": "HIGH-YIELD RULES",
    "9_radiopediadrill.txt": "RADIOPAEDIA DRILL RULES (FUTURE)",
    "outputrule.txt": "OUTPUT / TSV RULES",
}

# Watch settings
POLL_SECONDS = 0.35     # how often to check for changes
DEBOUNCE_SECONDS = 0.25 # coalesce rapid consecutive saves


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace").strip()


def banner(title: str, fname: str) -> str:
    line = "═" * 78
    return (
        f"\n{line}\n"
        f"SECTION: {title}\n"
        f"FILE:    {fname}\n"
        f"{line}\n"
    )


def snapshot(files: list[Path]) -> dict[str, tuple[float, int]]:
    """
    Returns a dict of filename -> (mtime, size) to robustly detect changes.
    """
    snap: dict[str, tuple[float, int]] = {}
    for f in files:
        stat = f.stat()
        snap[f.name] = (stat.st_mtime, stat.st_size)
    return snap


def build() -> None:
    missing = [f for f in ORDER if not (PROMPT_DIR / f).exists()]
    if missing:
        raise FileNotFoundError(
            "Missing files:\n- " + "\n- ".join(missing) +
            "\n\nFix filenames or update ORDER."
        )

    parts: list[str] = []
    built_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    parts.append(
        "=== FULL PROMPT (AUTO-GENERATED) ===\n"
        f"Built: {built_at}\n"
        "Do not edit this file directly; edit the source section files instead.\n"
    )

    for fname in ORDER:
        path = PROMPT_DIR / fname
        title = LABELS.get(fname, fname)
        content = read_text(path)

        if not content:
            parts.append(banner(title + " (EMPTY)", fname))
            parts.append("[EMPTY SECTION]\n")
            continue

        parts.append(banner(title, fname))
        parts.append(content + "\n")

    merged = "\n".join(parts).strip() + "\n"
    OUTPUT_FILE.write_text(merged, encoding="utf-8")
    print(f"✅ Built: {OUTPUT_FILE.resolve()}")


def watch() -> None:
    files = [PROMPT_DIR / f for f in ORDER]

    # Initial build
    build()
    last_snap = snapshot(files)
    print(f"👀 Watching for changes… (Ctrl+C to stop)")

    last_change_time: float | None = None

    while True:
        time.sleep(POLL_SECONDS)

        try:
            new_snap = snapshot(files)
        except FileNotFoundError:
            # If a file is temporarily missing during rename/save, wait and retry.
            continue

        if new_snap != last_snap:
            last_snap = new_snap
            last_change_time = time.time()

        # Debounce: wait a moment for multi-file writes to finish
        if last_change_time is not None and (time.time() - last_change_time) >= DEBOUNCE_SECONDS:
            try:
                build()
            except Exception as e:
                print(f"⚠️ Build error: {e}")
            last_change_time = None


if __name__ == "__main__":
    try:
        watch()
    except KeyboardInterrupt:
        print("\n🛑 Stopped.")
        sys.exit(0)