from __future__ import annotations

from datetime import datetime
from pathlib import Path
import sys
import time

PROMPT_DIR = Path(".")
OUTPUT_FILE = PROMPT_DIR / "FULL_PROMPT.txt"

ORDER = [
    "0_systemrules.txt",
    "0B_entitydefinitionrules.txt",
    "1_notetypestructure.txt",
    "2A_sourcehierarchy_normal.txt",
    "2B_wholesourcecoverageaudit.txt",
    "2C_summaryrule.txt",
    "2D_examapproachrules.txt",
    "2E_articledecompositionrules.txt",
    "2F_masteryprogressionrules.txt",
    "2G_adaptivegenerationrules.txt",
    "3_cardtypesrules.txt",
    "3B_fieldmatrix_normal.txt",
    "imagerules.txt",
    "4_Unknown.txt",
    "5_differentialdrillsrules.txt",
    "6_mechanism.txt",
    "7_boardstrap.txt",
    "8_highyield.txt",
    "9_radiopediadrill.txt",
    "tagrules_normal.txt",
    "outputrule.txt",
]

LABELS = {
    "0_systemrules.txt": "SYSTEM RULES",
    "0B_entitydefinitionrules.txt": "ENTITY DEFINITION RULES",
    "1_notetypestructure.txt": "NOTE TYPE STRUCTURE",
    "2A_sourcehierarchy_normal.txt": "SOURCE HIERARCHY (NORMAL ENGINE)",
    "2B_wholesourcecoverageaudit.txt": "WHOLE SOURCE COVERAGE AUDIT",
    "2C_summaryrule.txt": "SUMMARY RULE",
    "2D_examapproachrules.txt": "EXAM APPROACH RULES",
    "2E_articledecompositionrules.txt": "ARTICLE DECOMPOSITION RULES",
    "2F_masteryprogressionrules.txt": "MASTERY PROGRESSION RULES",
    "2G_adaptivegenerationrules.txt": "ADAPTIVE GENERATION RULES",
    "3_cardtypesrules.txt": "CARD TYPES + TRIGGERS",
    "3B_fieldmatrix_normal.txt": "NORMAL FIELD MATRIX",
    "imagerules.txt": "IMAGE RULES",
    "4_Unknown.txt": "UNKNOWN CARD RULES",
    "5_differentialdrillsrules.txt": "DIFFERENTIAL DRILL RULES",
    "6_mechanism.txt": "MECHANISM CARD RULES",
    "7_boardstrap.txt": "BOARDS TRAP RULES",
    "8_highyield.txt": "HIGH-YIELD RULES",
    "9_radiopediadrill.txt": "RADIOPAEDIA DRILL RULES (FUTURE)",
    "tagrules_normal.txt": "NORMAL TAG RULES",
    "outputrule.txt": "OUTPUT / TSV RULES",
}

POLL_SECONDS = 0.35
DEBOUNCE_SECONDS = 0.25


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace").strip()


def banner(title: str, fname: str) -> str:
    line = "=" * 78
    return (
        f"\n{line}\n"
        f"SECTION: {title}\n"
        f"FILE:    {fname}\n"
        f"{line}\n"
    )


def snapshot(files: list[Path]) -> dict[str, tuple[float, int]]:
    snap: dict[str, tuple[float, int]] = {}
    for file_path in files:
        stat = file_path.stat()
        snap[file_path.name] = (stat.st_mtime, stat.st_size)
    return snap


def build() -> None:
    missing = [file_name for file_name in ORDER if not (PROMPT_DIR / file_name).exists()]
    if missing:
        raise FileNotFoundError(
            "Missing files:\n- " + "\n- ".join(missing) + "\n\nFix filenames or update ORDER."
        )

    parts: list[str] = []
    built_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    parts.append(
        "=== FULL PROMPT (AUTO-GENERATED) ===\n"
        f"Built: {built_at}\n"
        "Do not edit this file directly; edit the source section files instead.\n"
    )

    for file_name in ORDER:
        path = PROMPT_DIR / file_name
        title = LABELS.get(file_name, file_name)
        content = read_text(path)

        if not content:
            parts.append(banner(f"{title} (EMPTY)", file_name))
            parts.append("[EMPTY SECTION]\n")
            continue

        parts.append(banner(title, file_name))
        parts.append(content + "\n")

    merged = "\n".join(parts).strip() + "\n"
    OUTPUT_FILE.write_text(merged, encoding="utf-8")
    print(f"Built: {OUTPUT_FILE.resolve()}")


def watch() -> None:
    files = [PROMPT_DIR / file_name for file_name in ORDER]

    build()
    last_snap = snapshot(files)
    print("Watching for changes... (Ctrl+C to stop)")

    last_change_time: float | None = None

    while True:
        time.sleep(POLL_SECONDS)

        try:
            new_snap = snapshot(files)
        except FileNotFoundError:
            continue

        if new_snap != last_snap:
            last_snap = new_snap
            last_change_time = time.time()

        if last_change_time is not None and (time.time() - last_change_time) >= DEBOUNCE_SECONDS:
            try:
                build()
            except Exception as exc:
                print(f"Build error: {exc}")
            last_change_time = None


if __name__ == "__main__":
    try:
        watch()
    except KeyboardInterrupt:
        print("\nStopped.")
        sys.exit(0)
